Added InstructorComments models and entities, CourseStars model and e…
JamshidMaruf/Arcana pull request #19
Opened 2024-05-03 14:06 UTC by kholmirzayevAhmadjon

…ntities

2024-05-03 15:12 UTC, fullstack-Maestro approved these changes

2024-05-04 12:56 UTC, makhammadsoliyev commented on src/Arcana.Domain/Entities/Instructors/InstructorComment.cs
> +public class InstructorComment
Where is auditable

2024-05-04 13:01 UTC, makhammadsoliyev requested changes
Requested changes

2024-05-04 20:33 UTC, makhammadsoliyev approved these changes

2024-05-04 20:33 UTC, merged